[package]
name = "wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
dyn-clone = "1.0.20"
num = "0.4.3"
num_enum = "0.7.5"
serde = {version = "1.0.228", features = ["derive"]}
serde_json = "1.0.145"
wasm-bindgen = "0.2.106"
